// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBOUgzybj_i8NAnw_s2WRarXVAxWQJfbyc',
    appId: '1:500700097695:web:4e9a217fd999f80346c6aa',
    messagingSenderId: '500700097695',
    projectId: 'flash-chat-28410',
    authDomain: 'flash-chat-28410.firebaseapp.com',
    storageBucket: 'flash-chat-28410.appspot.com',
    measurementId: 'G-BQF4QF0SNS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWm6hcUnwnE6Cg2Lm245aAPBzFyLUdT9c',
    appId: '1:500700097695:android:a91b39a8c1b13ec946c6aa',
    messagingSenderId: '500700097695',
    projectId: 'flash-chat-28410',
    storageBucket: 'flash-chat-28410.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyF4VxQJqRAC3oic1_lBACKxpP9j6qkks',
    appId: '1:500700097695:ios:0e3376a48485504346c6aa',
    messagingSenderId: '500700097695',
    projectId: 'flash-chat-28410',
    storageBucket: 'flash-chat-28410.appspot.com',
    iosClientId: '500700097695-72k1ceghq1g8n9qjfdkdkl7ljo25lo2a.apps.googleusercontent.com',
    iosBundleId: 'com.example.flash-chat',
  );
}
